MODEL: "content_textcnn" # 模型名
PRIORITY: P2
GIT:
  addr: $REPO_PaddleRec
  path: $ROOT_PATH/PaddleRec
  branch: $content_textcnn_BRANCH

ENV:
  PADDLE_ON_MODEL_CE: $PADDLE_ON_MODEL_CE

VARIABLES:
  model_scripts_path: scripts/content_textcnn/ #脚本的路径
  model_log_path: log/content_textcnn/

EXEC:
  exec_cases: [DATA_PROC,TRAIN,INFER]
  exec_priority: [p0]
  exec_tag: $EXEC_TAG
#测试套
DATA_PROC:
  -
    tag: linux_down_data
    priority: p0
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh data_proc.sh down_senti_clas


TRAIN: # 训练步骤
  -
    tag: linux_dy_gpu1
    priority: p0
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_CUDA  #取值为None，则不设置

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh linux_dy_gpu1_con rank_linux_dy_gpu1_con

    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 0.7710104
        threshold: 0.0
        actived: True
        evaluation: "+"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/S_rank_textcnn_linux_dy_gpu1_con_T.log
    kpis: #kpi指标
      auc:
        latest: True
        kpi_base: 0.929062
        threshold: 0.0
        actived: True
        evaluation: "+"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/S_rank_textcnn_linux_dy_gpu1_con_I.log


  -
    tag: linux_dy_gpu2
    priority: p0
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_MULTI_CUDA  #取值为None，则不设置

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh linux_dy_gpu2_con rank_textcnn_linux_dy_gpu2_con

    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 0.7710104
        threshold: 0.0
        actived: True
        evaluation: "+"
        unit_repr: None

    output: $ROOT_PATH/$model_log_path/rrank_textcnn_linux_dy_gpu2_con_dist_train_log/workerlog.0
    kpis: #kpi指标
      auc:
        latest: True
        kpi_base: 0.929062
        threshold: 0.0
        actived: True
        evaluation: "+"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/rank_textcnn_linux_dy_gpu2_con_dist_infer_log/workerlog.0


  -
    tag: linux_dy_cpu
    priority: p0   # dy_cpu
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh linux_dy_cpu_con rank_textcnn_linux_dy_cpu_con

    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 0.7710104
        threshold: 0.0
        actived: True
        evaluation: "+"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/S_rank_textcnn_linux_dy_cpu_con_T.log
    kpis: #kpi指标
      auc:
        latest: True
        kpi_base: 0.929062
        threshold: 0.0
        actived: True
        evaluation: "+"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/S_rank_textcnn_linux_dy_cpu_con_I.log

  -
    tag: linux_st_gpu1  # st_gpu1
    priority: p0
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_CUDA  #取值为None，则不设置

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh linux_st_gpu1_con rank_textcnn_linux_st_gpu1_con

    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 0.7710104
        threshold: 0.0
        actived: True
        evaluation: "+"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/S_rank_textcnn_linux_st_gpu1_con_T.log
    kpis: #kpi指标
      auc:
        latest: True
        kpi_base: 0.929062
        threshold: 0.0
        actived: True
        evaluation: "+"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/S_rank_textcnn_linux_st_gpu1_con_I.log


  -
    tag: linux_st_gpu2  # st_gpu1
    priority: p0
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_MULTI_CUDA  #取值为None，则不设置

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh linux_st_gpu1_con rank_textcnn_linux_st_gpu1_con
    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 0.7710104
        threshold: 0.0
        actived: True
        evaluation: "+"
        unit_repr: None

    output: $ROOT_PATH/$model_log_path/rank_textcnn_linux_st_gpu2_con_dist_train_log/workerlog.0
    kpis: #kpi指标
      auc:
        latest: True
        kpi_base: 0.929062
        threshold: 0.0
        actived: True
        evaluation: "+"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/rank_textcnn_linux_st_gpu2_con_dist_infer_log/workerlog.0



  -
    tag: linux_st_cpu # st_cpu
    priority: p0
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh linux_st_cpu_con rank_textcnn_linux_st_cpu_con

    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 0.7710104
        threshold: 0.0
        actived: True
        evaluation: "+"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/S_rank_textcnn_linux_st_cpu_con_T.log
    kpis: #kpi指标
      auc:
        latest: True
        kpi_base: 0.929062
        threshold: 0.0
        actived: True
        evaluation: "+"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/S_rank_textcnn_linux_st_cpu_con_I.log
