MODEL: "match_dssm" # 模型名
PRIORITY: P0
GIT:
  addr: $REPO_PaddleRec
  path: $ROOT_PATH/PaddleRec
  branch: $match_dssm_BRANCH

ENV:
  PADDLE_ON_MODEL_CE: $PADDLE_ON_MODEL_CE

VARIABLES:
  model_scripts_path: scripts/match_dssm/ #脚本的路径
  model_log_path: log/match_dssm/

EXEC:
  exec_cases: [DATA_PROC,TRAIN]
  exec_priority: [p0]
  exec_tag: $EXEC_TAG
#测试套
DATA_PROC:
  -
    tag: linux_down_data
    priority: p0
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh data_proc.sh down_BQ_dssm

TRAIN: # 训练步骤
  -
    tag: linux_dy_gpu1
    priority: p0  # dy_gpu1
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_CUDA  #取值为None，则不设置

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh linux_dy_gpu1 match_dssm_linux_dy_gpu1

    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 0.31326857
        threshold: 0.02
        actived: True
        evaluation: "-"
        unit_repr: None
      time:
        latest: True
        kpi_base: 610
        threshold: 0.2
        actived: True
        evaluation: "-"
        unit_repr: "s"
    output: $ROOT_PATH/$model_log_path/S_match_dssm_linux_dy_gpu1.log
  -
    tag: linux_dy_gpu2  # dy_gpu2
    priority: p0  # dy_gpu2
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_MULTI_CUDA  #取值为None，则不设置

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh linux_dy_gpu2 match_dssm_linux_dy_gpu2

    kpis: #kpi指标
      auc:
        latest: True
        kpi_base: 0.795307
        threshold: 0.02
        actived: True
        evaluation: "+"
        unit_repr: None
      time:
        latest: True
        kpi_base: 11683.32
        threshold: 0.2
        actived: True
        evaluation: "-"
        unit_repr: "s"

    output: $ROOT_PATH/$model_log_path/match_dssm_linux_dy_gpu2_dist_log/workerlog.0
  -
    tag: linux_dy_cpu   # dy_cpu
    priority: p0   # dy_cpu
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh linux_dy_cpu match_dssm_linux_dy_cpu

    kpis: #kpi指标
      auc:
        latest: True
        kpi_base: 0.795307
        threshold: 0.02
        actived: True
        evaluation: "+"
        unit_repr: None
      time:
        latest: True
        kpi_base: 11683.32
        threshold: 0.2
        actived: True
        evaluation: "-"
        unit_repr: "s"

    output: $ROOT_PATH/$model_log_path/S_match_dssm_linux_dy_cpu.log

  -
    tag: linux_st_gpu1  # st_gpu1
    priority: p0  # st_gpu1
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_CUDA  #取值为None，则不设置

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh linux_st_gpu1 match_dssm_linux_st_gpu1

    kpis: #kpi指标
      auc:
        latest: True
        kpi_base: 0.795307
        threshold: 0.02
        actived: True
        evaluation: "+"
        unit_repr: None
      time:
        latest: True
        kpi_base: 11683.32
        threshold: 0.2
        actived: True
        evaluation: "-"
        unit_repr: "s"
    output: $ROOT_PATH/$model_log_path/S_match_dssm_linux_st_gpu1.log
  -
    tag: linux_st_gpu2  # st_gpu2
    priority: p0  # st_gpu2
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_MULTI_CUDA  #取值为None，则不设置

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh linux_st_gpu2 match_dssm_linux_st_gpu2

    kpis: #kpi指标
      auc:
        latest: True
        kpi_base: 0.795307
        threshold: 0.02
        actived: True
        evaluation: "+"
        unit_repr: None
      time:
        latest: True
        kpi_base: 11683.32
        threshold: 0.2
        actived: True
        evaluation: "-"
        unit_repr: "s"

    output: $ROOT_PATH/$model_log_path/match_dssm_linux_st_gpu2_dist_log/workerlog.0

  -
    tag: linux_st_cpu # st_cpu
    priority: p0 # st_cpu
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh linux_st_cpu match_dssm_linux_st_cpu

    kpis: #kpi指标
      auc:
        latest: True
        kpi_base: 0.795307
        threshold: 0.02
        actived: True
        evaluation: "+"
        unit_repr: None
      time:
        latest: True
        kpi_base: 11683.32
        threshold: 0.2
        actived: True
        evaluation: "-"
        unit_repr: "s"

    output: $ROOT_PATH/$model_log_path/S_match_dssm_linux_st_cpu.log


INFER:
  - #可以有多步
    tag: linux_dy_gpu1
    priority: p0
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_CUDA  #取值为None，则不设置
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh infer.sh linux_dy_gpu1 match_dssm_infer_linux_dy_gpu1

    kpis: #kpi指标
      PNR:
        latest: True
        kpi_base: 0.8000
        threshold: 0.02
        actived: True
        evaluation: "+"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/S_match_dssm_infer_linux_dy_gpu1_pair.log
  -
    tag: linux_dy_gpu2
    priority: p0
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_MULTI_CUDA  #取值为None，则不设置

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh infer.sh linux_dy_gpu2 match_dssm_infer_linux_dy_gpu2
    kpis: #kpi指标
      auc:
        latest: True
        kpi_base: 0.798875
        threshold: 0.02
        actived: True
        evaluation: "+"
        unit_repr: None
      time:
        latest: True
        kpi_base: 538.40
        threshold: 0.2
        actived: True
        evaluation: "-"
        unit_repr: "s"

    output: $ROOT_PATH/$model_log_path/S_match_dssm_infer_linux_dy_gpu2_pair.log
  -
    tag: linux_dy_cpu
    priority: p0
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh infer.sh linux_dy_cpu match_dssm_infer_linux_dy_cpu

    kpis: #kpi指标
      auc:
        latest: True
        kpi_base: 0.798875
        threshold: 0.02
        actived: True
        evaluation: "+"
        unit_repr: None
      time:
        latest: True
        kpi_base: 538.40
        threshold: 0.2
        actived: True
        evaluation: "-"
        unit_repr: "s"

    output: $ROOT_PATH/$model_log_path/S_match_dssm_infer_linux_dy_cpu_pair.log
  - #可以有多步
    tag: linux_st_gpu1
    priority: p0
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_CUDA  #取值为None，则不设置
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh infer.sh linux_st_gpu1 match_dssm_infer_linux_st_gpu1

    kpis: #kpi指标
      auc:
        latest: True
        kpi_base: 0.798875
        threshold: 0.02
        actived: True
        evaluation: "+"
        unit_repr: None
      time:
        latest: True
        kpi_base: 538.40
        threshold: 0.2
        actived: True
        evaluation: "-"
        unit_repr: "s"
    output: $ROOT_PATH/$model_log_path/S_match_dssm_infer_linux_st_gpu1_pair.log
  -
    tag: linux_st_gpu2
    priority: p0
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_MULTI_CUDA  #取值为None，则不设置

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh infer.sh linux_st_gpu2 match_dssm_infer_linux_st_gpu2

    kpis: #kpi指标
      auc:
        latest: True
        kpi_base: 0.798875
        threshold: 0.02
        actived: True
        evaluation: "+"
        unit_repr: None
      time:
        latest: True
        kpi_base: 538.40
        threshold: 0.2
        actived: True
        evaluation: "-"
        unit_repr: "s"

    output: $ROOT_PATH/$model_log_path/S_match_dssm_infer_linux_st_gpu2_pair.log
  -
    tag: linux_st_cpu
    priority: p0
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh infer.sh linux_st_cpu match_dssm_infer_linux_st_cpu

    kpis: #kpi指标
      auc:
        latest: True
        kpi_base: 0.798875
        threshold: 0.02
        actived: True
        evaluation: "+"
        unit_repr: None
      time:
        latest: True
        kpi_base: 538.40
        threshold: 0.2
        actived: True
        evaluation: "-"
        unit_repr: "s"

    output: $ROOT_PATH/$model_log_path/S_match_dssm_infer_linux_st_cpu_pair.log


