MODEL: "rank_wide_deep" # 模型名
PRIORITY: P2
GIT:
  addr: $REPO_PaddleRec
  path: $ROOT_PATH/PaddleRec
  branch: $rank_wide_deep_BRANCH

ENV:
  PADDLE_ON_MODEL_CE: $PADDLE_ON_MODEL_CE

VARIABLES:
  model_scripts_path: scripts/rank_wide_deep/ #脚本的路径
  model_log_path: log/rank_wide_deep/

EXEC:
  exec_cases: [DATA_PROC,TRAIN,INFER]
  exec_priority: [p0]
  exec_tag: $EXEC_TAG
#测试套
DATA_PROC:
  -
    tag: linux_down_data
    priority: p0
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh data_proc.sh down_criteo

TRAIN: # 训练步骤
  -
    tag: linux_dy_gpu1
    priority: p0
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_CUDA  #取值为None，则不设置

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh linux_dy_gpu1 rank_wide_deep_linux_dy_gpu1

    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 0.7710104
        threshold: 0.0
        actived: True
        evaluation: "+"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/S_rank_wide_deep_linux_dy_gpu1_T.log

    kpis: #kpi指标
      auc:
        latest: True
        kpi_base: 0.929062
        threshold: 0.0
        actived: True
        evaluation: "+"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/S_rank_wide_deep_linux_dy_gpu1_I.log

  -
    tag: linux_dy_gpu1_con
    priority: p1
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_CUDA  #取值为None，则不设置

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh linux_dy_gpu1_con rank_linux_dy_gpu1_con

    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 0.7710104
        threshold: 0.0
        actived: True
        evaluation: "+"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/S_rank_wide_deep_linux_dy_gpu1_con_T.log
    kpis: #kpi指标
      auc:
        latest: True
        kpi_base: 0.929062
        threshold: 0.0
        actived: True
        evaluation: "+"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/S_rank_wide_deep_linux_dy_gpu1_con_I.log


  -
    tag: linux_dy_gpu2
    priority: p0
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_CUDA  #取值为None，则不设置

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh linux_dy_gpu2 rank_wide_deep_linux_dy_gpu2

    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 0.7710104
        threshold: 0.0
        actived: True
        evaluation: "+"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/rank_wide_deep_linux_dy_gpu2_dist_train_log/workerlog.0

    kpis: #kpi指标
      auc:
        latest: True
        kpi_base: 0.929062
        threshold: 0.0
        actived: True
        evaluation: "+"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/rank_wide_deep_linux_dy_gpu2_dist_infer_log/workerlog.0

  -
    tag: linux_dy_gpu2_con
    priority: p1
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_MULTI_CUDA  #取值为None，则不设置

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh linux_dy_gpu2_con rank_wide_deep_linux_dy_gpu2_con

    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 0.7710104
        threshold: 0.0
        actived: True
        evaluation: "+"
        unit_repr: None

    output: $ROOT_PATH/$model_log_path/rrank_wide_deep_linux_dy_gpu2_con_dist_train_log/workerlog.0
    kpis: #kpi指标
      auc:
        latest: True
        kpi_base: 0.929062
        threshold: 0.0
        actived: True
        evaluation: "+"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/rank_wide_deep_linux_dy_gpu2_con_dist_infer_log/workerlog.0


  -
    tag: linux_dy_cpu
    priority: p0   # dy_cpu
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh linux_dy_cpu rank_wide_deep_linux_dy_cpu

    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 0.7710104
        threshold: 0.0
        actived: True
        evaluation: "+"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/S_rank_wide_deep_linux_dy_cpu_T.log
    kpis: #kpi指标
      auc:
        latest: True
        kpi_base: 0.929062
        threshold: 0.0
        actived: True
        evaluation: "+"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/S_rank_wide_deep_linux_dy_cpu_I.log

  -
    tag: linux_dy_cpu_con
    priority: p1   # dy_cpu
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh linux_dy_cpu_con rank_wide_deep_linux_dy_cpu_con

    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 0.7710104
        threshold: 0.0
        actived: True
        evaluation: "+"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/S_rank_wide_deep_linux_dy_cpu_con_T.log
    kpis: #kpi指标
      auc:
        latest: True
        kpi_base: 0.929062
        threshold: 0.0
        actived: True
        evaluation: "+"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/S_rank_wide_deep_linux_dy_cpu_con_I.log

  -
    tag: linux_st_gpu1  # st_gpu1
    priority: p0
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_CUDA  #取值为None，则不设置

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh linux_st_gpu1 rank_wide_deep_linux_st_gpu1

    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 0.7710104
        threshold: 0.0
        actived: True
        evaluation: "+"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/S_rank_wide_deep_linux_st_gpu1_T.log
    kpis: #kpi指标
      auc:
        latest: True
        kpi_base: 0.929062
        threshold: 0.0
        actived: True
        evaluation: "+"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/S_rank_wide_deep_linux_st_gpu1_I.log

  -
    tag: linux_st_gpu1_con  # st_gpu1
    priority: p1
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_CUDA  #取值为None，则不设置

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh linux_st_gpu1_con rank_wide_deep_linux_st_gpu1_con

    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 0.7710104
        threshold: 0.0
        actived: True
        evaluation: "+"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/S_rank_wide_deep_linux_st_gpu1_con_T.log
    kpis: #kpi指标
      auc:
        latest: True
        kpi_base: 0.929062
        threshold: 0.0
        actived: True
        evaluation: "+"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/S_rank_wide_deep_linux_st_gpu1_con_I.log


  -
    tag: linux_st_gpu2  # st_gpu1
    priority: p0
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_CUDA  #取值为None，则不设置

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh linux_st_gpu2 rank_wide_deep_linux_st_gpu2

    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 0.7710104
        threshold: 0.0
        actived: True
        evaluation: "+"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/S_rank_wide_deep_linux_st_gpu2_T.log
    kpis: #kpi指标
      auc:
        latest: True
        kpi_base: 0.929062
        threshold: 0.0
        actived: True
        evaluation: "+"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/S_rank_wide_deep_linux_st_gpu2_I.log


  -
    tag: linux_st_gpu2_con  # linux_st_gpu2_con
    priority: p1
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_MULTI_CUDA  #取值为None，则不设置

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh linux_st_gpu1_con rank_wide_deep_linux_st_gpu1_con
    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 0.7710104
        threshold: 0.0
        actived: True
        evaluation: "+"
        unit_repr: None

    output: $ROOT_PATH/$model_log_path/rank_wide_deep_linux_st_gpu2_con_dist_train_log/workerlog.0
    kpis: #kpi指标
      auc:
        latest: True
        kpi_base: 0.929062
        threshold: 0.0
        actived: True
        evaluation: "+"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/rank_wide_deep_linux_st_gpu2_con_dist_infer_log/workerlog.0



  -
    tag: linux_st_cpu # st_cpu
    priority: p0
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh linux_st_cpu rank_wide_deep_linux_st_cpu

    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 0.7710104
        threshold: 0.0
        actived: True
        evaluation: "+"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/S_rank_wide_deep_linux_st_cpu_T.log
    kpis: #kpi指标
      auc:
        latest: True
        kpi_base: 0.929062
        threshold: 0.0
        actived: True
        evaluation: "+"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/S_rank_wide_deep_linux_st_cpu_I.log

  -
    tag: linux_st_cpu_con # st_cpu
    priority: p1
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh linux_st_cpu_con rank_wide_deep_linux_st_cpu_con

    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 0.7710104
        threshold: 0.0
        actived: True
        evaluation: "+"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/S_rank_wide_deep_linux_st_cpu_con_T.log
    kpis: #kpi指标
      auc:
        latest: True
        kpi_base: 0.929062
        threshold: 0.0
        actived: True
        evaluation: "+"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/S_rank_wide_deep_linux_st_cpu_con_I.log
