MODEL: "msra_ner" # 模型名
PRIORITY: P1
GIT:
  addr: $REPO_PaddleNLP
  path: $ROOT_PATH/models_repo
  branch: $msra_ner_BRANCH

ENV:
  PADDLE_ON_MODEL_CE: $PADDLE_ON_MODEL_CE

VARIABLES:
  model_scripts_path: scripts/msra_ner/ #脚本的路径
  model_log_path: log/msra_ner/

EXEC:
  exec_cases: [DATA_PROC,TRAIN,INFER,EVAL]
  exec_priority: [p0,p1]
  exec_tag: $EXEC_TAG

#测试套
DATA_PROC:
  -
    priority: p0
    tag: linux_download_data
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh data_proc.sh

TRAIN: # 训练步骤
  -
    priority: p0
    tag: linux_dy_gpu1
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_CUDA  #取值为None，则不设置

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh $XPU single

    kpis: #kpi指标
      precision:
        latest: True
        kpi_base: 0.860087
        threshold: 0.02
        actived: True
        evaluation: "+"
        unit_repr: "s"
      recall:
        latest: True
        kpi_base: 0.890344
        threshold: 0.02
        actived: True
        evaluation: "+"
        unit_repr: "s"
      f1:
        latest: True
        kpi_base: 0.874954
        threshold: 0.02
        actived: True
        evaluation: "+"
        unit_repr: "s"
    output: $ROOT_PATH/$model_log_path/train_single_$XPU.log
  -
    priority: p0
    tag: linux_dy_gpu2

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh $XPU multi $SET_MULTI_CUDA

    kpis: #kpi指标
      precision:
        latest: True
        kpi_base: 0.860087
        threshold: 0.02
        actived: True
        evaluation: "+"
        unit_repr: "s"
      recall:
        latest: True
        kpi_base: 0.890344
        threshold: 0.02
        actived: True
        evaluation: "+"
        unit_repr: "s"
      f1:
        latest: True
        kpi_base: 0.874954
        threshold: 0.02
        actived: True
        evaluation: "+"
        unit_repr: "s"
    output: $ROOT_PATH/$model_log_path/train_multi_$XPU.log

INFER:
  - 
    priority: p0
    tag: linux_dy_gpu1
    env: #去掉，自动调度
        CUDA_VISIBLE_DEVICES: $SET_CUDA
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh infer.sh $XPU 
    kpis:
      exit_code:
        latest: True
        kpi_base: 0
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/infer_$XPU.log

EVAL:
  - #可以有多步
    priority: p1
    tag: linux_dy_gpu1
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_CUDA
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh eval.sh $XPU
    kpis: #kpi指标
      precision:
        latest: True
        kpi_base: 0.809076
        threshold: 0.02
        actived: True
        evaluation: "+"
        unit_repr: "s"
      recall:
        latest: True
        kpi_base: 0.854042
        threshold: 0.02
        actived: True
        evaluation: "+"
        unit_repr: "s"
      f1:
        latest: True
        kpi_base: 0.830951
        threshold: 0.02
        actived: True
        evaluation: "+"
        unit_repr: "s"
    output: $ROOT_PATH/$model_log_path/eval_$XPU.log


