MODEL: "tcn" # 模型名
PRIORITY: P2
GIT:
  addr: $REPO_PaddleNLP
  path: $ROOT_PATH/models_repo
  branch: $TCN_BRANCH

ENV:
  http_proxy: $HTTP_PROXY
  https_proxy: $HTTPS_PROXY
  PADDLE_ON_MODEL_CE: $PADDLE_ON_MODEL_CE

VARIABLES:
  model_scripts_path: scripts/tcn/ #脚本的路径
  model_log_path: log/tcn/

EXEC:
  exec_cases: [DATA_PROC,TRAIN,INFER]
  exec_priority: [p0,p1]
  exec_tag: $EXEC_TAG

#测试套
DATA_PROC:
  -
    priority: p0
    tag: linux_download_data
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh data_proc.sh

TRAIN: # 训练步骤
  -
    priority: p0
    tag: linux_dy_gpu1
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_CUDA  #取值为None，则不设置

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh $XPU 'single'

    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 7.376870
        threshold: 0.01
        actived: True
        evaluation: "-"
        unit_repr: "s"
    output: $ROOT_PATH/$model_log_path/train_single_$XPU.log

  -
    priority: p1
    tag: linux_dy_gpu2
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_MULTI_CUDA  #取值为None，则不设置

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh $XPU 'multi'

    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 7.376870
        threshold: 0.01
        actived: True
        evaluation: "-"
        unit_repr: "s"
    output: $ROOT_PATH/$model_log_path/train_multi_$XPU.log

  -
    priority: p2
    tag: linux_dy_gpu1
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_CUDA  #取值为None，则不设置

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh 'recv' $XPU 

    kpis: #kpi指标
      loss:
        kpi_base: 7.376870
        threshold: 0.01
        actived: True
        evaluation: "-"
        unit_repr: "s"
    output: $ROOT_PATH/$model_log_path/train_recover.log

INFER:
  - 
    priority: p0
    tag: linux_dy_gpu1
    env: #去掉，自动调度
        CUDA_VISIBLE_DEVICES: $SET_CUDA
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh infer.sh $XPU
    kpis:
      exit_code:
        latest: True
        kpi_base: 0
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/infer_$XPU.log

