MODEL: "text_classification_pretrained" # 模型名
PRIORITY: P0
GIT:
  addr: $REPO_PaddleNLP
  path: $ROOT_PATH/models_repo
  branch: $TEXT_CLASSIFICATION_PRETRAINED_BRANCH

ENV:
  http_proxy: $HTTP_PROXY
  https_proxy: $HTTPS_PROXY
  PADDLE_ON_MODEL_CE: $PADDLE_ON_MODEL_CE

VARIABLES:
  model_scripts_path: scripts/text_classification_pretrained/ #脚本的路径
  model_log_path: log/text_classification_pretrained/

EXEC:
  exec_cases: $EXEC_CASES
  exec_priority: $EXEC_PRIORITY
  exec_tag: $EXEC_TAG


TRAIN: # 训练步骤
  -
    priority: p0
    tag: "linux_dy_gpu1"
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_CUDA  #取值为None，则不设置

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh $XPU "single" 

    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 0.18490
        threshold: 0.01
        actived: True
        evaluation: "-"
        unit_repr: "s"
    output: $ROOT_PATH/$model_log_path/train_single_$XPU.log

  -
    priority: p1
    tag: "linux_dy_gpu2"
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_MULTI_CUDA  #取值为None，则不设置

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh $XPU "multi" 

    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 0.16675
        threshold: 0.01
        actived: True
        evaluation: "-"
        unit_repr: "s"

      accu:
        latest: True
        kpi_base: 0.95250
        threshold: 0.01
        actived: True
        evaluation: "+"
        unit_repr: "s"
    output: $ROOT_PATH/$model_log_path/train_multi_$XPU.log

  -
    priority: p0
    tag: "linux_dy_cpu"
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh $XPU

    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 0.18155
        threshold: 0.01
        actived: True
        evaluation: "-"
        unit_repr: "s"

      accu:
        latest: True
        kpi_base: 0.95250
        threshold: 0.01
        actived: True
        evaluation: "+"
        unit_repr: "s"
    output: $ROOT_PATH/$model_log_path/train_$XPU.log

INFER:
  -
    priority: p0
    tag: "linux_dy_gpu1"
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_CUDA  #取值为None，则不设置

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh infer.sh $XPU "single"
    kpis:
      exit_code:
        latest: True
        kpi_base: 0
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None 
    output: $ROOT_PATH/$model_log_path/infer_single_$XPU.log


  -
    priority: p1
    tag: "linux_dy_gpu2"
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_MULTI_CUDA  #取值为None，则不设置

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh infer.sh $XPU "multi" 
    kpis:
      exit_code:
        latest: True
        kpi_base: 0
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/infer_multi_$XPU.log
    

