MODEL: "bigbird" # 模型名
PRIORITY: P1
GIT:
  addr: $REPO_PaddleNLP
  path: $ROOT_PATH/models_repo
  branch: $BIGBIRD_BRANCH

ENV:
  PADDLE_ON_MODEL_CE: $PADDLE_ON_MODEL_CE

VARIABLES:
  model_scripts_path: scripts/bigbird/ #脚本的路径
  model_log_path: log/bigbird/

EXEC:
  exec_cases: [DATA_PROC,TRAIN]
  exec_priority: [p0,p1]
  exec_tag: $EXEC_TAG

#测试套
DATA_PROC:
  -
    priority: p0
    tag: linux_download_data
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh data_proc.sh

TRAIN: # 训练步骤
  #pretrain
  -
    priority: p0
    tag: linux_dy_gpu1
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh $XPU 'bigbird-base-uncased' 'single' $SET_CUDA

    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 10.937229
        threshold: 0.01
        actived: True
        evaluation: "-"
        unit_repr: "s"
    output: $ROOT_PATH/$model_log_path/train_single_$XPU.log

  -
    priority: p1
    tag: linux_dy_gpu2
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh $XPU 'bigbird-base-uncased' 'multi' $SET_MULTI_CUDA

    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 10.993358
        threshold: 0.01
        actived: True
        evaluation: "-"
        unit_repr: "s"
    output: $ROOT_PATH/$model_log_path/train_multi_$XPU.log

  #finetune
  -
    priority: p9
    tag: 
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh finetune.sh

    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 10.937228
        threshold: 0.01
        actived: True
        evaluation: "-"
        unit_repr: "s"
    output: $ROOT_PATH/$model_log_path/bigbird-base-uncased-finetune.log

