MODEL: "glue" # 模型名
PRIORITY: P0
GIT:
  addr: $REPO_PaddleNLP
  path: $ROOT_PATH/models_repo
  branch: $GLUE_BRANCH

ENV:
  PADDLE_ON_MODEL_CE: $PADDLE_ON_MODEL_CE

VARIABLES:
  model_scripts_path: scripts/glue/ #脚本的路径
  model_log_path: log/glue/

EXEC:
  exec_cases: [TRAIN]
  exec_priority: [p0]
  exec_tag: $EXEC_TAG

#测试套
TRAIN: # 训练步骤
#ernie-2.0-en 未对齐#
  -
    priority: p0
    tag: linux_dy_gpu1
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_CUDA  #取值为None，则不设置

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh $XPU 'single' 'bert' 'bert-base-uncased' 'SST-2'

    kpis: #kpi指标
      acc:
        latest: True
        kpi_base: 0.5091743119266054
        threshold: 0.01
        actived: True
        evaluation: "+"
        unit_repr: "s"
    output: $ROOT_PATH/$model_log_path/train_bert-base-uncased_SST-2_single_$XPU.log

  -
    priority: p0
    tag: linux_dy_gpu2
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_MULTI_CUDA  #取值为None，则不设置

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh $XPU 'multi' 'bert' 'bert-base-uncased' 'SST-2'

    kpis: #kpi指标
      acc:
        latest: True
        kpi_base: 0.5091743119266054
        threshold: 0.01
        actived: True
        evaluation: "+"
        unit_repr: "s"
    output: $ROOT_PATH/$model_log_path/train_bert-base-uncased_SST-2_multi_$XPU.log

  -
    priority: p0
    tag: win_dy_gpu1
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_CUDA  #取值为None，则不设置

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: train.bat $XPU bert bert-base-uncased SST-2

    kpis: #kpi指标
      acc:
        latest: True
        kpi_base: 0.5091743119266054
        threshold: 0.01
        actived: True
        evaluation: "+"
        unit_repr: "s"
    output: $ROOT_PATH/$model_log_path/train_bert-base-uncased_SST-2_$XPU.log
