MODEL: "plato-2" # 模型名
PRIORITY: P1
GIT:
  addr: $REPO_PaddleNLP
  path: $ROOT_PATH/models_repo
  branch: $DGU_BRANCH


VARIABLES:
  model_scripts_path: scripts/plato-2/ #脚本的路径
  model_log_path: log/plato-2/

EXEC:
  exec_cases: [DATA_PROC, TRAIN]
  exec_priority: [p0,p1]
  exec_tag: $EXEC_TAG

#测试套
DATA_PROC:
  -
    priority: p0
    tag: linux_download_data
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh data_proc.sh

TRAIN: # 训练步骤
  -
    priority: p0
    tag: linux_dy_24_gpu1
    env:
      CUDA_VISIBLE_DEVICES: $SET_CUDA
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh 24_train.sh $XPU 'single'

    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 11.921639
        threshold: 0.001
        actived: True
        evaluation: "-"
        unit_repr: "s"
    output: $ROOT_PATH/$model_log_path/train_24_single_$XPU.log
  
  -
    priority: p0
    tag: linux_dy_24_gpu2
    env:
      CUDA_VISIBLE_DEVICES: $SET_MULTI_CUDA
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh 24_train.sh $XPU 'multi' 

    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 11.921639
        threshold: 0.001
        actived: True
        evaluation: "-"
        unit_repr: "s"
    output: $ROOT_PATH/$model_log_path/train_24_multi_$XPU.log

  -
    priority: p0
    tag: linux_dy_32_gpu2
    env:
      CUDA_VISIBLE_DEVICES: $SET_MULTI_CUDA
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh 32_train.sh $XPU 'multi' 

    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 11.921639
        threshold: 0.001
        actived: True
        evaluation: "-"
        unit_repr: "s"
    output: $ROOT_PATH/$model_log_path/train_32_multi_$XPU.log

