MODEL: "waybill_ie" # 模型名
PRIORITY: P0
GIT:
  addr: $REPO_PaddleNLP
  path: $ROOT_PATH/models_repo
  branch: $waybill_ie_BRANCH

ENV:
  PADDLE_ON_MODEL_CE: $PADDLE_ON_MODEL_CE

VARIABLES:
  model_scripts_path: scripts/waybill_ie/ #脚本的路径
  model_log_path: log/waybill_ie/

EXEC:
  exec_cases: [DATA_PROC,TRAIN,INFER]
  exec_priority: [p0,p1]
  exec_tag: $EXEC_TAG

#测试套
DATA_PROC:
  -
    priority: p0
    tag: linux_download_data
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh data_proc.sh

TRAIN: # 训练步骤
  -
    priority: p0
    tag: linux_gpu1_ernie
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_CUDA  #取值为None，则不设置

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh gpu ernie 

    kpis: #kpi指标
      Precision:
        latest: True
        kpi_base: 0.97417
        threshold: 0.01
        actived: True
        evaluation: "+"
        unit_repr: "s"
      Recall:
        latest: True
        kpi_base: 0.98318
        threshold: 0.01
        actived: True
        evaluation: "+"
        unit_repr: "s"
      F1:
        latest: True
        kpi_base: 0.97865
        threshold: 0.01
        actived: True
        evaluation: "+"
        unit_repr: "s"
    output: $ROOT_PATH/$model_log_path/train_gpu_ernie.log

  -
    priority: p0
    tag: linux_gpu1_bigru_crf
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_CUDA  #取值为None，则不设置

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh gpu bigru_crf 

    kpis: #kpi指标
      Precision:
        latest: True
        kpi_base: 0.87076
        threshold: 0.02
        actived: True
        evaluation: "+"
        unit_repr: "s"
      Recall:
        latest: True
        kpi_base: 0.90664
        threshold: 0.01
        actived: True
        evaluation: "+"
        unit_repr: "s"
      F1:
        latest: True
        kpi_base: 0.88834
        threshold: 0.02
        actived: True
        evaluation: "+"
        unit_repr: "s"
    output: $ROOT_PATH/$model_log_path/train_gpu_bigru_crf.log

  -
    priority: p0
    tag: linux_gpu1_ernie_crf
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_CUDA  #取值为None，则不设置

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: bash train.sh gpu ernie_crf 

    kpis: #kpi指标
      Precision:
        latest: True
        kpi_base: 0.885808
        threshold: 0.02
        actived: True
        evaluation: "+"
        unit_repr: "s"
      Recall:
        latest: True
        kpi_base: 0.913373
        threshold: 0.025
        actived: True
        evaluation: "+"
        unit_repr: "s"
      F1:
        latest: True
        kpi_base: 0.899379
        threshold: 0.02
        actived: True
        evaluation: "+"
        unit_repr: "s"
    output: $ROOT_PATH/$model_log_path/train_gpu_ernie_crf.log


